### ISSUE TITLE
Web cors

### ISSUE THREAD

**Issue by guillaumeboehm** [h7x4ABk3g/unofficial_jisho_api_dart#3]
Hello, I am trying to use your api on a flutter web app and I am getting CORS errors. I am not expert in CORS but I believe I cannot do anything about it on my side. Do you know if this is a problem with the way the Jisho API handles CORS?

**Comment by h7x4** [comment]
Hello!

I don't know for sure about the inner workings of your web app, but I believe that the Jisho CORS setup blocks you from pulling websites using javascript within a browser. As far as I know, there is no workaround for this, because the browser is in control of setting the Origin of the HTTP request. You're gonna have to set up a backend responsible for using the API and forwarding the data to the user in order to make this work.

**Comment by guillaumeboehm** [comment]
Ok that seems reasonable! Thanks for the reply.
